# This is a basic workflow to help you get started with Actions

name: Validate JSONs

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./tests/testSchema.json
          INPUT_JSONS: ./src/AllButtonSettings.json,./src/AllFilterPaneSettings.json,./src/AlwaysHaveBackgrounds.json,./src/AlwaysHaveOutlines.json,./src/HideVisualHeaders.json,./src/MaintainLayerOrder.json,./src/SetGlobalFonts_Minimal.json./src/BestDefaultsForCustomBackground_DarkTheme.json,./src/BestDefaultsForCustomBackground_LightTheme.json